[build]
  command = "npm run build"
  publish = "dist"

[context]
  # Single Page App fallback - serve index.html for client-side routing
  # Netlify also supports a _redirects file, but this keeps config in repo.
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
